version: '3.8'

services:
  hadoop-namenode-1:
    image: wxwmatt/hadoop-namenode:2.1.1-hadoop3.3.1-java8  
    container_name: hadoop-namenode-1
    platform: linux/arm64
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - namenode_1:/hadoop/dfs/name

  hadoop-namenode-2:
    image: wxwmatt/hadoop-namenode:2.1.1-hadoop3.3.1-java8  
    container_name: hadoop-namenode-2
    platform: linux/arm64
    ports:
      - "9871:9870"
      - "8021:8020"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - namenode_2:/hadoop/dfs/name

  hadoop-datanode-1:
    image: wxwmatt/hadoop-datanode:2.1.1-hadoop3.3.1-java8    
    container_name: hadoop-datanode-1
    platform: linux/arm64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-1:8020
      - HDFS_CONF_dfs_datanode_du_reserved=134217728
    volumes:
      - datanode_1:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode-1

  hadoop-datanode-2:
    image: wxwmatt/hadoop-datanode:2.1.1-hadoop3.3.1-java8    
    container_name: hadoop-datanode-2
    platform: linux/arm64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-1:8020
      - HDFS_CONF_dfs_datanode_du_reserved=134217728
    volumes:
      - datanode_2:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode-1

  hadoop-datanode-3:
    image: wxwmatt/hadoop-datanode:2.1.1-hadoop3.3.1-java8    
    container_name: hadoop-datanode-3
    platform: linux/arm64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-1:8020
      - HDFS_CONF_dfs_datanode_du_reserved=134217728
    volumes:
      - datanode_3:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode-1

  hadoop-datanode-4:
    image: wxwmatt/hadoop-datanode:2.1.1-hadoop3.3.1-java8    
    container_name: hadoop-datanode-4
    platform: linux/arm64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-1:8020
      - HDFS_CONF_dfs_datanode_du_reserved=134217728
    volumes:
      - datanode_4:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode-1

  hadoop-datanode-5:
    image: wxwmatt/hadoop-datanode:2.1.1-hadoop3.3.1-java8    
    container_name: hadoop-datanode-5
    platform: linux/arm64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode-1:8020
      - HDFS_CONF_dfs_datanode_du_reserved=134217728
    volumes:
      - datanode_5:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode-1

  spark-master:
    image: bitnami/spark:3.5.4-debian-12-r1
    container_name: spark-master
    platform: linux/arm64
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - hadoop-namenode-1
      - hadoop-namenode-2

  spark-worker:
    image: bitnami/spark:3.5.4-debian-12-r1
    container_name: spark-worker
    platform: linux/arm64
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master

  pyspark-client:
    image: jupyter/pyspark-notebook:aarch64-lab-4.0.6
    container_name: pyspark-client
    platform: linux/arm64/v8
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
      - PYSPARK_PYTHON=python3
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
      - hadoop-namenode-1
      - hadoop-namenode-2

volumes:
  namenode_1:
  namenode_2:
  datanode_1:
  datanode_2:
  datanode_3:
  datanode_4:
  datanode_5:
